development:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: slack_stripe_dev
  username: postgres
  password: postgres
  pool:     5

test:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: slack_stripe_test
  username: postgres
  password: postgres
  pool:     5

production:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: slack_stripe
  pool:     5
  username: postgres
  password: password

